# Generated by Django 5.1.4 on 2025-02-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowEventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbookingcustform',
            name='event_date_time',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='planitnowevents',
            name='eventDateTime',
            field=models.CharField(max_length=100),
        ),
    ]
