# Generated by Django 5.1.4 on 2025-02-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowEventApp', '0002_alter_eventbookingcustform_event_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbookingcustform',
            name='event_date_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventbookingcustform',
            name='ticket_quantity',
            field=models.IntegerField(),
        ),
    ]
