# Generated by Django 5.1.4 on 2025-02-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowEventApp', '0005_alter_bookingdetails_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
