# Generated by Django 5.1.4 on 2025-02-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowEventApp', '0006_alter_bookingdetails_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
