# Generated by Django 5.1.4 on 2025-04-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowEventApp', '0010_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitnowevents',
            name='totalTickets',
            field=models.IntegerField(default=100),
        ),
    ]
