# Generated by Django 5.1.4 on 2025-04-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowEventApp', '0011_planitnowevents_totaltickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/member.png', upload_to='profile_images/'),
        ),
    ]
