# Generated by Django 5.1.4 on 2025-04-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowEventApp', '0013_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbookingcustform',
            name='city',
        ),
        migrations.RemoveField(
            model_name='eventbookingcustform',
            name='state',
        ),
    ]
